### ISSUE TITLE
The script still has the redirection to YouTube

### ISSUE THREAD

**Issue by driversti** [Humberd/Stuff-unlocked#1]
In the script, we have a link to Zordacz's file that allows him to make undesired changes.
This is the link: `dl.dropboxusercontent.com/s/165fdfgga2lb3se/u.json`
You should store it on your own server (for example on Github) and remove the following settings there:
`"x":"setTimeout(y=>location.href=\"//youtu.be/9jK-NcRmVcw\",10000)"`

**Comment by Humberd** [comment]
Removed dropbox links in these commits

https://github.com/Humberd/Stuff-unlocked/commit/3af08d389564dfbeda38e772d30ae78efd3edcc3
https://github.com/Humberd/Stuff-unlocked/commit/1eb268f07dfceebb6a4d64ce45f73aa25adf8ff4
