### ISSUE TITLE
Autofight doesn't work

### ISSUE THREAD

**Issue by BruceD666** [Humberd/Stuff-unlocked#4]
Dear Humberd,

first of all thank you for making the script work again and releasing new, fixed versions. 
I would like to ask about the autofighter:

When I click on the launch button, first it seems to be launched, but returns to main page with "https://www.erepublik.com/en?_=nocache_=1611517411987" (the number increases every time) text in the address bar.

What causes this problem, is it planned to be fixed in future?

Best regards,
BruceD666

**Comment by Humberd** [comment]
I hate to say it, but it works for me :D Did you disable the previous Stuff++ script?

**Comment by BruceD666** [comment]
Yes, I deleted the previous script, and also cleared cache and cookies, but the problem still exists, on my home PC and at workstation PC as well. Both of them uses up to date Win10 and Chrome browser, I have no idea about the reason.

**Comment by Humberd** [comment]
Unfortunately, I don't have a way to reproduce it. Can you try it using Firefox? I'd like to know if it might be something with your Chrome instance.

**Comment by BruceD666** [comment]
I tried it using Firefox, and it works, so I would like to apologize for flagging it as an issue.
So the problem is in the Chrome somewhere, but I have no idea where... :)
Thank you for your help.

**Comment by driversti** [comment]
@BruceD666 try to press the **RESET** button on the script's dialog. It could help.
Of course, after this action, you have to set up the script again

**Comment by BruceD666** [comment]
@driversti

Thank you for the option, I tried it, the problem is still the same.

**Comment by Humberd** [comment]
Well, it looks like they are killing the legacy mode anyway

> Starting February 8th 2021 (Day 4,829, 00:00) Legacy Fight Mode will be retired from the game. Click here to switch to Deployment Mode.

**Comment by BruceD666** [comment]
I asked an other player about it, and the autofighter is working well, he's using Chrome as well.
And it's also strange, that I didn't see any other complaints like this from players at the chat walls, so may be the problem is in my system somewhere (included 2 PC-s, so it's also strange), it can be a new X-file. :) 
If I don't find the problem, I will use Firefox, which has no problem with the autofighter part of the script.
