### ISSUE TITLE
Problem with auto power spin

### ISSUE THREAD

**Issue by konradlb** [Humberd/Stuff-unlocked#9]
The power spin automation does not work with the new power spin version available for a month. The first click on the "spin" button starts the roulette, but then the automat has a problem with confirmation of receiving the prize and therefore stops.

![image](https://github.com/Humberd/Stuff-unlocked/assets/12851999/0fb15c59-9ca3-42f8-b20f-d021b342d7a0)

**Comment by Humberd** [comment]
Working on it #11
